/**
 * Debug utility for fixing export functionality
 */

// Wait for DOM to be loaded
window.addEventListener('DOMContentLoaded', () => {
    console.log('Debug export utility loaded and waiting for page initialization');
    
    // Add a slight delay to ensure everything is initialized
    setTimeout(setupExportButton, 500);
});

/**
 * Set up the export button with a fixed implementation
 */
function setupExportButton() {
    const exportServerButton = document.getElementById('exportForServer');
    if (exportServerButton) {
        // Remove existing event listeners by cloning the button
        const newButton = exportServerButton.cloneNode(true);
        exportServerButton.parentNode.replaceChild(newButton, exportServerButton);
        
        // Add our fixed implementation
        newButton.addEventListener('click', manualExportForServer);
        console.log('Export button handler replaced with fixed implementation');
    } else {
        console.warn('Export for server button not found');
    }
}

/**
 * Manual implementation to export server configuration file
 */
function manualExportForServer() {
    console.log('Manual export for server function called');
    
    try {
        // Try to get state from any available StateManager instance
        let state = null;
        
        // Get all state managers
        const stateManagers = Object.values(window).filter(obj => 
            obj && typeof obj === 'object' && obj.constructor && 
            obj.constructor.name === 'StateManager');
        
        if (stateManagers.length > 0) {
            state = stateManagers[0].getState();
            console.log('Got state from StateManager');
        } else {
            // Try to get UI state from controls
            state = getStateFromControls();
            console.log('Generated state from UI controls');
        }
        
        if (!state) {
            state = getDefaultSettings();
            console.log('Using default settings as state');
        }
        
        // Create the export data
        const data = {
            version: "1.0.0",
            timestamp: new Date().toISOString(),
            meta: {
                warning: 'DO NOT EDIT THIS FILE MANUALLY. Use the Search Pro Settings Panel.',
                generatedAt: new Date().toISOString(),
                generatedBy: 'Search Pro Config Panel v2.0.0'
            },
            settings: state,
            deployment: {
                source: "settings-panel",
                target: "server-config"
            }
        };

        // Create download
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);

        const a = document.createElement('a');
        a.href = url;
        a.download = 'search-config.json';
        document.body.appendChild(a);
        a.click();

        setTimeout(() => {
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }, 100);
        
        // Show deployment instructions
        showDeploymentInstructions();
        
        // Show success notification
        showNotification('Server configuration exported', 'success');
        
        console.log('Manual export completed successfully');
        return true;
    } catch (error) {
        console.error('Manual export failed:', error);
        showNotification('Failed to export server configuration: ' + error.message, 'error');
        return false;
    }
}

/**
 * Extract settings state from UI controls
 */
function getStateFromControls() {
    const state = {};
    
    // Get all controls with data-path attribute
    const controls = document.querySelectorAll('[data-path]');
    
    controls.forEach(control => {
        const path = control.dataset.path;
        let value;
        
        // Get value based on control type
        if (control.type === 'checkbox') {
            value = control.checked;
        } else if (control.type === 'number') {
            value = parseFloat(control.value);
        } else if (control.type === 'range') {
            value = parseFloat(control.value);
        } else if (control.tagName === 'SELECT') {
            value = control.value;
            // Convert string values to appropriate types
            if (value === 'true') value = true;
            else if (value === 'false') value = false;
            else if (value === '') value = null;
        } else {
            value = control.value;
        }
        
        // Set value at path
        setValueAtPath(state, path, value);
    });
    
    return state;
}

/**
 * Set a value at a specific path in an object
 */
function setValueAtPath(obj, path, value) {
    const parts = path.split('.');
    let current = obj;
    
    for (let i = 0; i < parts.length - 1; i++) {
        const part = parts[i];
        if (!current[part]) {
            current[part] = {};
        }
        current = current[part];
    }
    
    current[parts[parts.length - 1]] = value;
}

/**
 * Get default settings fallback
 */
function getDefaultSettings() {
    return {
        appearance: {
            colors: {
                searchBackground: '#ffffff',
                searchText: '#1a1a1a',
                placeholderText: '#64748b',
                searchIcon: '#64748b',
                clearIcon: '#64748b',
                resultsBackground: '#ffffff',
                groupHeaderColor: '#475569',
                groupCountColor: '#94a3b8',
                resultHover: '#f1f5f9',
                resultBorderLeft: '#3b82f6',
                resultText: '#1e293b',
                resultSubtitle: '#64748b',
                resultIconColor: '#6e85f7',
                resultSubtextColor: '#64748b'
            },
            searchWidth: 350,
            searchResults: {
                maxHeight: 500
            }
        },
        theme: {
            useDarkMode: null,
            useSystemPreference: true,
            typography: {
                fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
                fontSize: 16,
                letterSpacing: 0
            }
        },
        display: {
            showGroupHeaders: true,
            showGroupCount: true,
            showIconsInResults: true,
            showSubtitlesInResults: true
        },
        includeContent: {
            unlabeledWithSubtitles: true,
            unlabeledWithTags: true,
            completelyBlank: false
        },
        filter: {
            mode: "none",
            elementTypes: {
                mode: "none"
            }
        },
        minSearchChars: 2
    };
}

/**
 * Show deployment instructions
 */
function showDeploymentInstructions() {
    // Create modal dialog
    const modal = document.createElement('div');
    modal.className = 'deployment-modal';
    modal.innerHTML = `
        <div class="deployment-modal-content">
            <h3>Server Deployment Instructions</h3>
            <p>To make these settings permanent across all browsers:</p>
            <ol>
                <li>Upload <code>search-config.json</code> to: <br>
                    <code>/search-pro/config/search-config.json</code> on your server</li>
                <li>The configuration will automatically load for all users</li>
                <li>You can now remove or restrict access to this settings page</li>
            </ol>
            <button class="primary-button close-modal">Got it</button>
        </div>
    `;
    
    // Add to document
    document.body.appendChild(modal);
    
    // Add event listener to close button
    modal.querySelector('.close-modal').addEventListener('click', () => {
        document.body.removeChild(modal);
    });
}

/**
 * Show notification message
 */
function showNotification(message, type = 'info') {
    // Create notification element
    const notification = document.createElement('div');
    notification.className = `notification ${type}`;
    notification.textContent = message;
    notification.style.position = 'fixed';
    notification.style.bottom = '20px';
    notification.style.right = '20px';
    notification.style.padding = '10px 20px';
    notification.style.backgroundColor = type === 'success' ? '#10b981' : 
                                       type === 'error' ? '#ef4444' :
                                       type === 'warning' ? '#f59e0b' : '#3b82f6';
    notification.style.color = 'white';
    notification.style.borderRadius = '4px';
    notification.style.boxShadow = '0 2px 5px rgba(0,0,0,0.2)';
    notification.style.zIndex = '9999';
    notification.style.transition = 'opacity 0.3s, transform 0.3s';
    notification.style.opacity = '0';
    notification.style.transform = 'translateY(20px)';
    
    // Add to document
    document.body.appendChild(notification);
    
    // Show notification
    setTimeout(() => {
        notification.style.opacity = '1';
        notification.style.transform = 'translateY(0)';
    }, 10);
    
    // Remove after delay
    setTimeout(() => {
        notification.style.opacity = '0';
        notification.style.transform = 'translateY(20px)';
        
        // Remove from DOM after animation
        setTimeout(() => {
            if (notification.parentNode) {
                document.body.removeChild(notification);
            }
        }, 300);
    }, 3000);
}
