/**
 * Debug utility for the exportForServer functionality
 */

window.addEventListener('DOMContentLoaded', () => {
    // Attach to the export button
    const exportServerButton = document.getElementById('exportForServer');
    if (exportServerButton) {
        exportServerButton.addEventListener('click', debugExportForServer);
    }
    
    console.log('Debug export utility loaded');
});

/**
 * Debug function to troubleshoot export issues
 */
function debugExportForServer() {
    console.log('Export for server button clicked');
    
    try {
        // Check if the UIManager instance exists
        const uiManagerInstances = Object.values(window).filter(obj => 
            obj && typeof obj === 'object' && obj.constructor && 
            obj.constructor.name === 'UIManager');
        
        console.log('Found UIManager instances:', uiManagerInstances.length);
        
        // Check if storageManager is initialized
        if (uiManagerInstances.length > 0) {
            const uiManager = uiManagerInstances[0];
            console.log('Storage manager exists:', !!uiManager._storageManager);
            console.log('Storage manager methods:', 
                        uiManager._storageManager ? 
                        Object.getOwnPropertyNames(Object.getPrototypeOf(uiManager._storageManager)) : 
                        'N/A');
            
            // Manual export implementation as fallback
            const state = uiManager._stateManager.getState();
            manualExportForServer(state);
        } else {
            console.error('No UIManager instance found');
        }
    } catch (error) {
        console.error('Debug export error:', error);
    }
}

/**
 * Manual implementation as a fallback
 */
function manualExportForServer(settings) {
    try {
        const data = {
            version: "1.0.0", // Hardcoded since we can't easily access getSchemaVersion
            timestamp: new Date().toISOString(),
            meta: {
                warning: 'DO NOT EDIT THIS FILE MANUALLY. Use the Search Pro Settings Panel.',
                generatedAt: new Date().toISOString(),
                generatedBy: 'Search Pro Settings Panel v2.0.0'
            },
            settings: settings
        };

        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);

        const a = document.createElement('a');
        a.href = url;
        a.download = 'search-config.json';
        document.body.appendChild(a);
        a.click();

        setTimeout(() => {
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }, 100);

        console.log('Manual export completed successfully');
        return true;
    } catch (error) {
        console.error('Manual export failed:', error);
        return false;
    }
}
